### PR TITLE
Add "dist-dir" command

### PR DESCRIPTION
**Pull request by dsturnbull**
For anything that wants to discover the directory that contains `setup-config`.
Also change `cabal configure` to `cabal new-configure`.

```
~/src/play/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-12.11/8.4.3/libexec/x86_64-osx-ghc-8.4.3/cabal-helper-1.0.0.0/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/Users/david/src/arbor/mayhem/hw-ip" "/Users/david/src/arbor/mayhem/hw-ip/dist-newstyle/build/x86_64-osx/ghc-8.4.3/hw-ip-0.4.1" dist-dir
[Just (ChResponseDistDir "dist-newstyle/build/x86_64-osx/ghc-8.4.3/hw-ip-0.4.1")]
```

### CODE REVIEW

**Comment by alanz** [comment]
So this patch effectively removes support for cabal old build in favour of new-build?

Is there any way we can continue to support old build?

**Comment by dsturnbull** [comment]
@alanz I don't think it does. `ghc-mod` doesn't need to call this `dist-dir` command if it's old-style (or stack) because those paths are static or done by other means.

**Comment by alanz** [comment]
Great, I am just confirming it locally, then will look at a merge.

Can you consider bringing this up to date with master? I had to add the 8.4.4 stack file as that is my current default compiler, so I was running the wrong version of hie initially.

Now rebuilding.

**Comment by alanz** [comment]
My experiments show that it does indeed still work for old style and stack projects, but I am getting test failures. 
I will begin merging/working through. But not to master on my repo, to a branch `cabal-new`.

**Comment by dsturnbull** [comment]
@alanz 👍

**Comment by alanz** [comment]
Merged into https://github.com/alanz/cabal-helper/tree/cabal-new

**Pull request closed without merging**
